import type { Metadata } from "next";
import "./globals.css";
import { SideBar } from "@components/SideBar";
import classnames from "classnames";
import { InterFont } from "../lib/fonts";
import { Providers } from "@components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classnames(InterFont.className, "h-screen")}>
        <Providers>
          <SideBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
